### ISSUE TITLE
Doesn't copy vendors folder in /dist

### ISSUE THREAD

**Issue by weiss-d** [HabedyOmid/Gulp-Masterfy-Assets#3]
Hi, Omid!
Looks like there is a problem still with vendor's js.
When I delete all folders in `/dist` and run `gulp build` it makes `css`, `img` and `js` folders, but not the `vendors` folder, which new script links in `index.html` refer to.

**Comment by HabedyOmid** [comment]
Please refer to README.md file for all the instructions. in order to copy vendor directory you have to use another command "gulp vendors" to simply copy the vendor folder under dist

**Comment by weiss-d** [comment]
Thanks!
